export const realNames = [
  "Giant Spider Games",
  "Devious Weasel Games",
  "Flying Frog Productions",
  "Tasty Minstrel Games",
  "Iron Kitten Games",
  "Daily Magic Games",
  "Green Couch Games",
  "Atomic Planet Entertainment",
  "Plaid Hat Games",
  "Albino Dragon",
  "Blue Orange Games",
  "Formal Ferret Games",
  "Purple Brain Creations",
  "White Goblin Games",
  "Kind Fortress",
  "Clever Mojo Games",
  "Space Cowboys",
  "Jolly Thinkers",
  "Devil Pig Games",
  "Orange Nebula",
  "Guru Fabric",
  "Funky Sheep",
  "Elephant Laboratories",
  "First Fish Games",
  "Burnt Island Games",
  "Sinister Fish Games",
  "Evil Hat Productions"
]
